/*
@TargetNode='localhost'
@GeneratedBy=runneradmin
@GenerationDate=02/08/2021 01:16:17
@GenerationHost=fv-az153-328
*/

instance of MSFT_RegistryResource as $MSFT_RegistryResource1ref
{
SourceInfo = "D:\\a\\CloudSOE\\CloudSOE\\guest-configuration\\WindowsLogonBanner.ps1::17::9::Registry";
 ValueType = "String";
 ModuleVersion = "2.12.0.0";
 Ensure = "Present";
 ValueName = "legalnoticecaption";
 ValueData = {
    "title"
};
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
 ModuleName = "PSDscResources";
 ResourceID = "[Registry]Ensure Windows logon banner title is set correctly";
 ConfigurationName = "WindowsLogonBanner";
};
instance of MSFT_RegistryResource as $MSFT_RegistryResource2ref
{
SourceInfo = "D:\\a\\CloudSOE\\CloudSOE\\guest-configuration\\WindowsLogonBanner.ps1::26::9::Registry";
 ValueType = "String";
 ModuleVersion = "2.12.0.0";
 Ensure = "Present";
 ValueName = "legalnoticetext";
 ValueData = {
    "text"
};
 Key = "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
 ModuleName = "PSDscResources";
 ResourceID = "[Registry]Ensure Windows logon banner text is set correctly";
 ConfigurationName = "WindowsLogonBanner";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="runneradmin";

                        GenerationDate="02/08/2021 01:16:17";

                        GenerationHost="fv-az153-328";

                        Name="WindowsLogonBanner";

                    };
