name: Build Guest Configuration policies

on:
  # Triggers the workflow on push to the guest-configuration folder
  push:
    paths: 
      - 'guest-configuration/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      

jobs:
  Compile-Guest-Configuration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile MOFs
        run: |
          Install-Module -Name PSDscResources -Force
          Install-Module -Name GuestConfiguration -Confirm:$false
          Set-Location "guest-configuration"          
          Get-ChildItem *.ps1 | % {
            & ('.\' + ($_.Name))
          }
          Get-ChildItem -Recurse *.mof | % {
            $GuestConfigurationFile = $_.FullName
            $GuestConfigurationName = (($_.Directory.Name) -split "_")[1]
            New-GuestConfigurationPackage -Name $GuestConfigurationName -Configuration $GuestConfigurationFile | Test-GuestConfigurationPackage
          }
            
      - name: Commit 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Compiled MOFs (actions)"
          git push

