name: Build Guest Configuration policies

on:
  # Triggers the workflow on push to the guest-configuration folder
  push:
    paths: 
      - 'guest-configuration/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      

jobs:
  Compile-MOF:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run compile script
        run: |
          Install-Module PSDscResources -Force
          Get-ChildItem -Recurse *.ps1 | % {Set-Location $_.Directory ; & ('.\' + ($_.Name))}
      - name: Commit 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Compiled MOFs (actions)"
          git push

