name: Build Guest Configuration policies

on:
  # Triggers the workflow on push to the guest-configuration folder
  push:
    paths: 
      - 'guest-configuration/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      

jobs:
  Compile-Guest-Configuration:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Compile MOFs
        run: |
          Install-Module -Name PSDscResources -Force
          Install-Module -Name GuestConfiguration -Force -AllowClobber -RequiredVersion 3.1.3
          Import-Module PSDesiredStateConfiguration
          Set-Location "guest-configuration"
          New-Item "MOF" -ItemType Directory -ErrorAction:SilentlyContinue
          New-Item "Packages" -ItemType Directory -ErrorAction:SilentlyContinue
          
          $PSFiles = Get-ChildItem *.ps1
          Set-Location "MOF"
          $PSFiles | % {
            & ($_.Fullname)
          }
          $MOFFiles = Get-ChildItem -Recurse *.mof 
          Set-Location ..
          $MOFFiles | % {
            $GuestConfigurationFile = $_.FullName
            $GuestConfigurationName = $_.Directory.Name
            New-GuestConfigurationPackage -Name $GuestConfigurationName -Configuration $GuestConfigurationFile -Path Packages -Force | Test-GuestConfigurationPackage
          }
            
      - name: Commit 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Compiled MOFs (actions)"
          git push

