name: Deploy to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Cancel previous deployment
        run: |
          az deployment sub cancel -n azureDeploy
        continue-on-error: true
      - name: Remove old resource group
        run: |
          az group delete --name CloudSOEImageRG -y 2> /dev/null
        continue-on-error: true
      - name: Wait for Github HTTP cache TTL
        uses: jakejarvis/wait-action@master
        with:
          time: '300s'
      - uses: actions/checkout@master
      - name: Azure deployment
        uses: azure/arm-deploy@v1
        with:
          template: https://raw.githubusercontent.com/jimmyfit/CloudSOE/master/azureDeploy.json
          parameters: policyScopeId=${{ secrets.TESTDEPLOYMENT_POLICYSCOPEID }} workspaceId=${{ secrets.TESTDEPLOYMENT_WORKSPACEID }}
          scope: subscription
          region: eastus
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
      - name: Wait for Policy to take effect
        uses: jakejarvis/wait-action@master
        with:
          time: '1800s'
      - name: Deploy the test VM - WS2019
        run: |
          az vm create \
          --resource-group CloudSOEImageRG \
          --name TestVM2019 \
          --admin-username ${{ secrets.TESTVM_USERNAME }} \
          --admin-password ${{ secrets.TESTVM_PASSWORD }} \
          --image ${{ secrets.TESTVM_IMAGENAME_2019 }} \
          --location eastus
      - name: Deploy the test VM - WS2016
        run: |
          az vm create \
          --resource-group CloudSOEImageRG \
          --name TestVM2016 \
          --admin-username ${{ secrets.TESTVM_USERNAME }} \
          --admin-password ${{ secrets.TESTVM_PASSWORD }} \
          --image ${{ secrets.TESTVM_IMAGENAME_2016 }} \
          --location eastus
          


