name: Deploy to Azure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Remove old resource group
        run: |
          az group delete --name CloudSOEImageRG -y 2> /dev/null
        continue-on-error: true
      - uses: actions/checkout@master
      - name: Azure deployment
        uses: azure/arm-deploy@v1
        with:
          template: ./azureDeploy.json
          scope: subscription
          region: eastus
      - name: Run Azure Image Builder build
        run: |
          az resource invoke-action \
           --resource-group CloudSOEImageRG \
           --resource-type  Microsoft.VirtualMachineImages/imageTemplates \
           -n WindowsServer2019SOE \
           --action Run                  


